spring.profiles.active=dev

spring.application.name=Small_Business_BE
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/smb_db
spring.datasource.username=root
spring.datasource.password=Hi1xSQLwzqa-?

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.base-url=http://localhost:8080

app.uploads.root=uploads
app.uploads.logos=${app.uploads.root}/logos
app.uploads.photos=${app.uploads.root}/photos
app.uploads.documents=${app.uploads.root}/documents

file.photo-dir=${app.uploads.photos}
file.document-dir=${app.uploads.documents}

spring.web.resources.static-locations=file:${app.uploads.root}/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-post-size=10485760

server.servlet.session.timeout=30m
spring.jpa.open-in-view=false

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

