POST http://localhost:8080/api/products

{
  "name": "phone",
  "article": null,
  "vendorArticle": "venart",
  "purchasingPrice": 10.50,
  "sellingPrice": 15.00,

        @NotBlank(message = "{validation.notBlank}")
        String unitOfMeasurement,

        @DecimalMin(value = "0.0", inclusive = true, message = "{validation.weight.min}")
        @Digits(integer = 5, fraction = 3, message = "{validation.weight.digits}")
        Float weight,

        @Size(max = 50, message = "{validation.max.size}")
        String size,

        @NotNull(message = "{validation.notNull}")
        ProductCategory productCategory,

        @Size(min = 3, max = 1024, message = "{validation.description.size}")
        @Pattern(regexp = DESCRIPTION_REGEX, message = "{description.Pattern.message}")
        String description,

        @Size(max = 20, message = "{validation.max.size}")
        String customsNumber,

        @PastOrPresent(message = "{validation.dateOfLastPurchase.pastOrPresent}")
        Date dateOfLastPurchase)
}